server:
  port: 5555
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    oauth2-server:
      path: /**
      serviceId: oauth2server
    microservice-1:
      path: /api/micro1/**
      serviceId: microservice1
    microservice-2:
      path: /api/micro2/**
      serviceId: microservice2
spring:
  application:
    name: zuul-server
management:
  endpoint:
    routes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
