version: '3.3'
services:
  eureka-server:
    build:
      context: .
      dockerfile: DockerFile-eureka-server
      args:
        JAR_FILE: eureka-server-0.0.1-SNAPSHOT.jar
    ports:
      - '8761:8761'
    environment:
      DEUREKA_SERVER: 'http://eureka-server:8761/eureka'
    networks:
      - micro
    image: 'joko/eureka-server'

  config-server:
    build:
      context: .
      dockerfile: DockerFile-config-server
      args:
        JAR_FILE: config-server-0.0.1-SNAPSHOT.jar
    ports:
      - '8888:8888'
    networks:
      - micro
    environment:
      spring.cloud.config.server.git.uri: 'https://github.com/marcosechague/spring-cloud-demo-properties'
    image: 'joko/config-server'

  microservice1:
    build:
      context: .
      dockerfile: DockerFile-microservice1
      args:
        JAR_FILE: microservice1-0.0.1-SNAPSHOT.jar
    links:
      - config-server:config-server
      - eureka-server:eureka-server
    depends_on:
      - config-server
      - eureka-server
    networks:
      - micro
    environment:
      server.port: 5555
      eureka.instance.preferIpAddress: 'true'
      client.registerWithEureka: 'true'
      eureka.client.serviceUrl.defaultZone: 'http://eureka-server:8761/eureka/'
      spring.config.uri: 'http://config-server:8888'
      spring.config.enabled: 'true'

  microservice2:
    build:
      context: .
      dockerfile: DockerFile-microservice2
      args:
        JAR_FILE: microservice2-0.0.1-SNAPSHOT.jar
    links:
      - config-server:config-server
      - eureka-server:eureka-server
    depends_on:
      - config-server
      - eureka-server
    networks:
      - micro
    environment:
      server.port: 5555
      eureka.instance.preferIpAddress: 'true'
      client.registerWithEureka: 'true'
      eureka.client.serviceUrl.defaultZone: 'http://eureka-server:8761/eureka/'
      spring.config.uri: 'http://config-server:8888'
      spring.config.enabled: 'true'
    image: 'joko/microservice2'

  cloud-gateway:
    build:
      context: .
      dockerfile: DockerFile-cloud-gateway
      args:
        JAR_FILE: cloud-gateway-0.0.1-SNAPSHOT.jar
    ports:
      - '5555:5555'
    links:
      - config-server:config-server
      - eureka-server:eureka-server
    depends_on:
      - config-server
      - eureka-server
    networks:
      - micro
    environment:
      eureka.client.serviceUrl.defaultZone: 'http://eureka-server:8761/eureka/'
    image: 'joko/cloud-gateway'

networks:
  micro:
    driver: bridge
