spring:
    database:
        driverClassName: "org.postgresql.Driver"
    datasource:
        password: "p0stgr@s"
        platform: "postgres"
        testWhileIdle: "true"
        url: "jdbc:postgresql://database:5432/spring-cloud-demo-db"
        username: "postgres"
        validationQuery: "SELECT 1"
    jpa:
        database: "POSTGRESQL"
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.PostgreSQLDialect"
        show-sql: "true"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
